//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanetsManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planets_Robots
    {
        public System.Guid Id { get; set; }
        public System.Guid IdPlanet { get; set; }
        public System.Guid IdRobot { get; set; }
    
        public virtual Planet Planet { get; set; }
        public virtual Robot Robot { get; set; }
        public virtual Planet Planet1 { get; set; }
        public virtual Robot Robot1 { get; set; }
    }
}
